server:
  port: 8080

spring:
  config:
    import: optional:file:./config/oauth.yml
  web:
    resources:
      static-locations: classpath:/static/,classpath:/images/,file:./uploads/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Для разработки
  datasource:
    url: jdbc:mysql://89.35.130.222:3306/s156_PGWSite?useSSL=false&serverTimezone=UTC
    username: u156_kOg0BtJwSj
    password: IY+BHWniVPjzVtreUER+@KwS
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false
  mvc:
    static-path-pattern: /**
  jpa:
    hibernate:
        ddl-auto: update
    properties:
        format_sql: true
        connection:
          isolation: 2 # READ_COMMITTED
    show-sql: true
  messages:
    basename: lang/messages
    encoding: UTF-8
    cache-duration: 0
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            resource: DEBUG
        security: DEBUG