server:
  port: 8080
  tomcat:
    max-http-form-post-data-size: 100MB # Default, but good to know
    max-swallow-size: -1 # Allows unlimited size for multipart requests, if needed
    max-part-count: 1000
    max-http-form-post-size: 20971520  # 20MB

spring:
  config:
    import: optional:file:./config/oauth.yml
  web:
    resources:
      static-locations: classpath:/static/,classpath:/images/,file:./uploads/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Для разработки
  datasource:
    jdbc-url: jdbc:mysql://89.35.130.222:3306/s156_PGWSite?useSSL=false&serverTimezone=UTC
    username: u156_kOg0BtJwSj
    password: IY+BHWniVPjzVtreUER+@KwS
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 600000
      maxLifetime: 1800000 
  statistics-datasource:
    jdbc-url: jdbc:mysql://89.35.130.222:3306/s156_WorkSwap_Statistic?useSSL=false&serverTimezone=UTC
    username: u156_CaJhtIAXUw
    password: hYcuB@iC=UK5.u8H80F4IkD^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: false
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      enabled: true                # Включить поддержку multipart (по умолчанию true, но лучше указать явно)
      max-file-size: 100MB          # Максимальный размер одного файла
      max-request-size: 200MB       # Максимальный общий размер всех файлов в одном запросе
      file-size-threshold: 2MB      # Порог после которого данные пишутся на диск (0 — сразу на диск)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      connection:
        isolationLevel: 2 # READ_COMMITTED
    show-sql: false
  messages:
    basename: lang/messages
    encoding: UTF-8
    cache-duration: 0
logging:
  level:
    org:
      springframework:
        web:
          multipart: DEBUG
          servlet:
            resource: DEBUG
        security: DEBUG